### ISSUE TITLE
Double tap is determined as a single tap at the same time

### ISSUE THREAD

**Issue by rosen-krantz** [britzl/defold-input#27] opened 2022-02-10 06:33 UTC
I used defold-input in my project to detect gestures like horizontal and vertical swipes and taps. And I faced this behavior: 
- when I make single tap, it is detected as a single tap
- when I make double tap, it is detected as a single tap first, then as a double tap

I thought that something wrong in my project and made a new simple test project where is only one script from the [example](https://github.com/britzl/defold-input/blob/master/in/gesture.md#using-gesturelua).
And the behavior is the same. Double click make two prints.

Is there something additional checks that I need to do?

**Comment by britzl** [comment] 2022-02-14 05:45
It is impossible to know if the first tap will be part of a double tap or not, and you really don't want to delay sending information about the first tap to the client.

This is by design and will not change.

**Closed by britzl** 2022-02-14 05:45 UTC
